name       : python-tensorflow-estimator
version    : 2.10.0
release    : 7
source     :
    - https://github.com/tensorflow/estimator/archive/refs/tags/v2.10.tar.gz : 60df309377cf4e584ca20198f9639beb685d50616395f50770fc0999092d6d85
license    : Apache-2.0
component  : programming.python
summary    : TensorFlow Estimator
description: |
    TensorFlow Estimator is a high-level TensorFlow API that greatly simplifies machine learning programming. Estimators encapsulate training, evaluation, prediction, and exporting for your model.
networking : yes
builddeps  :
    - bazel
    - python-keras
    - python-packaging
    - python-protobuf
    - python-termcolor
    - python-wheel
    - python-wrapt
    - tensorflow
rundeps    :
    - python-keras
    - tensorflow
build      : |
    export PYTHON_BIN_PATH=/usr/bin/python3
    bazel build //tensorflow_estimator/tools/pip_package:build_pip_package
    bazel-bin/tensorflow_estimator/tools/pip_package/build_pip_package /tmp
    bazel shutdown
install    : |
    python3 -m pip install --no-deps --root=$installdir /tmp/tensorflow_estimator*.whl
