name       : python-tensorflow-estimator
version    : 1.14.0
release    : 2
source     :
    - https://github.com/tensorflow/estimator/archive/v1.14.0.tar.gz : 1f0b80b8067a52cc33bbe390d34791eb3e12453c506daa1b4c8fc07fbf962d9f
license    : Apache-2.0
component  : programming.python
summary    : TensorFlow Estimator
description: |
    TensorFlow Estimator is a high-level TensorFlow API that greatly simplifies machine learning programming. Estimators encapsulate training, evaluation, prediction, and exporting for your model.
builddeps  :
    - bazel
    - python-protobuf
    - python-termcolor
    - python-wheel
    - python-wrapt
    - tensorflow
rundeps    :
    - tensorflow
build      : |
    export PYTHON_BIN_PATH=python3
    bazel build --incompatible_use_python_toolchains //tensorflow_estimator/tools/pip_package:build_pip_package
    bazel-bin/tensorflow_estimator/tools/pip_package/build_pip_package /tmp
    bazel shutdown
install    : |
    pip3 install --no-deps --root=$installdir /tmp/tensorflow_estimator*.whl
