name       : python-tensorflow-estimator
version    : 2.1.0
release    : 3
source     :
    - https://github.com/tensorflow/estimator/archive/v2.1.tar.gz : 1d74c8181b981748976fa33ad97d3434c3cf2b7e29a0b00861365fe8329dbc4e
license    : Apache-2.0
component  : programming.python
summary    : TensorFlow Estimator
description: |
    TensorFlow Estimator is a high-level TensorFlow API that greatly simplifies machine learning programming. Estimators encapsulate training, evaluation, prediction, and exporting for your model.
networking : yes
builddeps  :
    - bazel
    - python-protobuf
    - python-termcolor
    - python-wheel
    - python-wrapt
    - tensorflow
rundeps    :
    - tensorflow
build      : |
    export PYTHON_BIN_PATH=/usr/bin/python3
    bazel build //tensorflow_estimator/tools/pip_package:build_pip_package
    bazel-bin/tensorflow_estimator/tools/pip_package/build_pip_package /tmp
    bazel shutdown
install    : |
    pip3 install --no-deps --root=$installdir /tmp/tensorflow_estimator*.whl
