name       : python-tensorflow-estimator
version    : 2.6.0
release    : 6
source     :
    - https://github.com/tensorflow/estimator/archive/refs/tags/v2.6.0.tar.gz : 947705c60c50da0b4a8ceec1bc058aaf6bf567a7efdcd50d5173ebf6bafcf30f
license    : Apache-2.0
component  : programming.python
summary    : TensorFlow Estimator
description: |
    TensorFlow Estimator is a high-level TensorFlow API that greatly simplifies machine learning programming. Estimators encapsulate training, evaluation, prediction, and exporting for your model.
networking : yes
builddeps  :
    - bazel
    - python-keras
    - python-protobuf
    - python-termcolor
    - python-wheel
    - python-wrapt
    - tensorflow
rundeps    :
    - python-keras
    - tensorflow
build      : |
    export PYTHON_BIN_PATH=/usr/bin/python3
    bazel build //tensorflow_estimator/tools/pip_package:build_pip_package
    bazel-bin/tensorflow_estimator/tools/pip_package/build_pip_package /tmp
    bazel shutdown
install    : |
    python3 -m pip install --no-deps --root=$installdir /tmp/tensorflow_estimator*.whl
